''' Generate golden reference vectors for the iOS app's math, from the SAME
    validated pipeline the study uses (`astro` + `corrections`).

    Emits two files under `ios/CelestialFixMVP/Tests/`:
      * `golden_vectors.json`  -- machine-readable, for any consumer.
      * `GoldenVectors.swift`  -- a Swift array literal so `PipelineTests` can
        check the ported math WITHOUT bundling a resource.

    Each record carries a body's geographic position (Dec, GHA, distance) and,
    from an observer, the geometric geocentric altitude/azimuth plus the apparent
    altitude and its constituent corrections (HP, parallax, refraction).  The
    Swift port must reproduce:
      * `apparentFromGeometric(geometricAltDeg, distanceKm)  == apparentAltDeg`
      * `geometricFromApparent(apparentAltDeg, distanceKm)   == geometricAltDeg`
    to a tight tolerance (pure formula port), and its own on-device ephemeris to
    a looser one (the truncated series vs the arcsec almanac).

    Run:  python -m imu_fusion.export_golden

    (c) 2026.  MIT License (see LICENSE file).
'''

import json
import os
from datetime import datetime, timezone

from .astro import (body_gp, gp_dec_gha, body_distance_km,
                    predicted_altitude, predicted_azimuth)
from . import corrections as C

# Representative samples: two epochs, observers spanning latitudes, both bodies.
# Chosen so altitudes range from low (large parallax) to high (refraction-only).
_SAMPLES = [
    ("2026-03-24 12:00:00", 40.0, -5.0),
    ("2026-03-24 12:00:00", 10.0, 60.0),
    ("2026-03-24 18:30:00", 51.5, 0.0),
    ("2026-06-15 03:00:00", -33.9, 18.4),
    ("2026-09-21 22:15:00", 35.7, 139.7),
    ("2026-12-10 06:45:00", 25.0, -80.0),
]
_BODIES = ("Moon", "Sun")


def build_records():
    ''' Return the list of golden records (dicts), skipping below-horizon /
        near-horizon geometry (< 6 deg) where the models are ill-conditioned. '''
    recs = []
    for iso, lat, lon in _SAMPLES:
        for body in _BODIES:
            gp = body_gp(body, iso)
            dec, gha = gp_dec_gha(gp)
            dist = body_distance_km(body, iso)
            geo_alt = predicted_altitude(lat, lon, gp)
            if geo_alt < 6.0:
                continue
            az = predicted_azimuth(lat, lon, gp)
            hp = C.horizontal_parallax_deg(dist)
            para = C.parallax_in_altitude_deg(geo_alt, dist)
            app = C.apparent_from_geometric(geo_alt, dist)
            refr = C.refraction_deg(app)
            recs.append(dict(
                utc=iso, body=body, obsLatDeg=lat, obsLonDeg=lon,
                decDeg=round(dec, 6), ghaDeg=round(gha, 6),
                distanceKm=round(dist, 1),
                geometricAltDeg=round(geo_alt, 6),
                azimuthDeg=round(az, 6),
                hpDeg=round(hp, 6),
                parallaxDeg=round(para, 6),
                refractionDeg=round(refr, 6),
                apparentAltDeg=round(app, 6),
            ))
    return recs


_SWIFT_HEADER = '''// GoldenVectors.swift — GENERATED by imu_fusion/export_golden.py. Do not edit.
//
// Reference vectors from the validated Python pipeline (astro + corrections),
// cross-checked against astropy/ERFA in validate_ephemeris.py.  PipelineTests
// checks the ported Swift math against these.  © 2026 MIT.

struct GoldenVector {
    let utc: String
    let body: String
    let obsLatDeg: Double, obsLonDeg: Double
    let decDeg: Double, ghaDeg: Double, distanceKm: Double
    let geometricAltDeg: Double, azimuthDeg: Double
    let hpDeg: Double, parallaxDeg: Double, refractionDeg: Double
    let apparentAltDeg: Double
}

let goldenVectors: [GoldenVector] = [
'''


def _swift_literal(recs) -> str:
    rows = []
    for r in recs:
        rows.append(
            f'    GoldenVector(utc: "{r["utc"]}", body: "{r["body"]}", '
            f'obsLatDeg: {r["obsLatDeg"]}, obsLonDeg: {r["obsLonDeg"]}, '
            f'decDeg: {r["decDeg"]}, ghaDeg: {r["ghaDeg"]}, '
            f'distanceKm: {r["distanceKm"]}, '
            f'geometricAltDeg: {r["geometricAltDeg"]}, azimuthDeg: {r["azimuthDeg"]}, '
            f'hpDeg: {r["hpDeg"]}, parallaxDeg: {r["parallaxDeg"]}, '
            f'refractionDeg: {r["refractionDeg"]}, '
            f'apparentAltDeg: {r["apparentAltDeg"]}),')
    return _SWIFT_HEADER + "\n".join(rows) + "\n]\n"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.normpath(os.path.join(
        here, "..", "ios", "CelestialFixMVP", "Tests"))
    os.makedirs(out_dir, exist_ok=True)
    recs = build_records()

    json_path = os.path.join(out_dir, "golden_vectors.json")
    with open(json_path, "w") as f:
        json.dump(recs, f, indent=2)
        f.write("\n")

    swift_path = os.path.join(out_dir, "GoldenVectors.swift")
    with open(swift_path, "w") as f:
        f.write(_swift_literal(recs))

    print(f"wrote {len(recs)} golden vectors:")
    print(f"  {json_path}")
    print(f"  {swift_path}")


if __name__ == "__main__":
    main()
