// GoldenVectors.swift — GENERATED by imu_fusion/export_golden.py. Do not edit.
//
// Reference vectors from the validated Python pipeline (astro + corrections),
// cross-checked against astropy/ERFA in validate_ephemeris.py.  PipelineTests
// checks the ported Swift math against these.  © 2026 MIT.

struct GoldenVector {
    let utc: String
    let body: String
    let obsLatDeg: Double, obsLonDeg: Double
    let decDeg: Double, ghaDeg: Double, distanceKm: Double
    let geometricAltDeg: Double, azimuthDeg: Double
    let hpDeg: Double, parallaxDeg: Double, refractionDeg: Double
    let apparentAltDeg: Double
}

let goldenVectors: [GoldenVector] = [
    GoldenVector(utc: "2026-03-24 12:00:00", body: "Moon", obsLatDeg: 40.0, obsLonDeg: -5.0, decDeg: 27.92, ghaDeg: 287.105, distanceKm: 368943.8, geometricAltDeg: 26.290455, azimuthDeg: 74.500609, hpDeg: 0.99, parallaxDeg: 0.887586, refractionDeg: 0.034654, apparentAltDeg: 25.430787),
    GoldenVector(utc: "2026-03-24 12:00:00", body: "Sun", obsLatDeg: 40.0, obsLonDeg: -5.0, decDeg: 1.533333, ghaDeg: 358.438333, distanceKm: 149597870.7, geometricAltDeg: 51.073622, azimuthDeg: 169.525119, hpDeg: 0.002441, parallaxDeg: 0.001534, refractionDeg: 0.013387, apparentAltDeg: 51.085475),
    GoldenVector(utc: "2026-03-24 12:00:00", body: "Moon", obsLatDeg: 10.0, obsLonDeg: 60.0, decDeg: 27.92, ghaDeg: 287.105, distanceKm: 368943.8, geometricAltDeg: 68.363494, azimuthDeg: 32.330229, hpDeg: 0.99, parallaxDeg: 0.365014, refractionDeg: 0.006697, apparentAltDeg: 67.999227),
    GoldenVector(utc: "2026-03-24 12:00:00", body: "Sun", obsLatDeg: 10.0, obsLonDeg: 60.0, decDeg: 1.533333, ghaDeg: 358.438333, distanceKm: 149597870.7, geometricAltDeg: 31.327293, azimuthDeg: 265.669192, hpDeg: 0.002441, parallaxDeg: 0.002086, refractionDeg: 0.027126, apparentAltDeg: 31.352334),
    GoldenVector(utc: "2026-03-24 18:30:00", body: "Moon", obsLatDeg: 51.5, obsLonDeg: 0.0, decDeg: 28.205, ghaDeg: 20.51, distanceKm: 369565.9, geometricAltDeg: 62.092676, azimuthDeg: 221.277123, hpDeg: 0.988333, parallaxDeg: 0.462564, refractionDeg: 0.008955, apparentAltDeg: 61.631922),
    GoldenVector(utc: "2026-09-21 22:15:00", body: "Sun", obsLatDeg: 35.7, obsLonDeg: 139.7, decDeg: 0.419167, ghaDeg: 155.517917, distanceKm: 149597870.7, geometricAltDeg: 20.50309, azimuthDeg: 105.016053, hpDeg: 0.002441, parallaxDeg: 0.002287, refractionDeg: 0.043771, apparentAltDeg: 20.544575),
]
